name = "rtc-signaling"
main = "index.js"
compatibility_date = "2023-11-26"

[durable_objects]
bindings = [{name = "ROOM", class_name = "Room"}]

[[migrations]]
tag = "v1" # This can be any string that uniquely identifies a migration
new_classes = ["Room"] # The list of new Durable Object classes